baseurl = "/"
theme = "ad-blog-theme"
languageCode = "en-US"
canonifyurls = true

# NOTE: https://gohugo.io/templates/pagination/#configuration
[pagination]
disableAliases = false
pagerSize = 6
path = 'page'

[params]
title = "Algorithms and Data Structures"
subtitle = "Musings on Computer Science"
copyright = "© 2018"

cover = "img/unibib.jpg"
description = "Musings on Computer Science Topics by the Team of the Chair of Algorithms and Data Structures under Prof. Dr. Hannah Bast"
metaDescription = ""
customCSS = []
RSSLink = ""

githubName = "ad-freiburg"

#logo = "img/logo.png"
orgName = "University of Freiburg"
orgWebsite = "https://ad.cs.uni-freiburg.de"
orgDescription = ""

showSupport = false

pageNotFoundTitle = "404 - Page not found"

#casper or caspertwo
singleViewStyle = "casper"

[services]
[services.disqus]
shortname = ""
[services.googleAnalytics]
id = ''

[permalinks]
post = "/post/:slug/"

[[menu.main]]
name = "Home"
url = "/"
weight = 200

#[[menu.main]]
#  name = "Some Topic"
#  url = "/tags/thetag"
#  weight = 100

#[[menu.main]]
#  name = "News"
#  url = "/categories/news/"
#  weight = 99

[[menu.main]]
name = "Research"
url = "/categories/research/"
weight = 98

[markup.goldmark.renderer]
unsafe = true
